os: osx
osx_image: xcode9.2
language: swift
before_install:
  - cd Demo
  - bundle install
  - bundle exec pod install
script:
  - xcodebuild -workspace Demo.xcworkspace -scheme Demo -destination 'platform=iOS Simulator,OS=9.3,name=iPhone 5s' build-for-testing test
